name: Continuous Integration

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Install sbt
      uses: coursier/setup-action@v1
      with:
        apps: sbt

    - name: Cache SBT dependencies
      uses: actions/cache@v3
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}
        restore-keys: |
          ${{ runner.os }}-sbt-

    - name: Run tests and upload to Coveralls
      run: sbt clean coverage test coverageReport coveralls
